"""Street graphs: the grid that water pipes (and sewers) follow.

Three sources are supported:

* :func:`synthetic_streets` — a procedurally generated old-city ward used as the
  offline default. It is placed at latitude/longitude (0, 0) on purpose so it
  can never be mistaken for a real place when exported to a GIS.
* :func:`load_overpass_json` — raw OpenStreetMap data as returned by the
  Overpass API (see :func:`fetch_osm` and ``upstream fetch-streets``).
* :func:`load_geojson` — any GeoJSON of LineStrings (e.g. exported from QGIS or
  overpass-turbo).
"""

from __future__ import annotations

import json
import math
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

import networkx as nx
import numpy as np

from ..geo import project, unproject

# OSM highway values along which distribution pipes are assumed to run.
HIGHWAY_KEEP = frozenset(
    {
        "trunk", "trunk_link", "primary", "primary_link", "secondary", "secondary_link",
        "tertiary", "tertiary_link", "unclassified", "residential", "living_street",
        "service", "road", "pedestrian",
    }
)

OSM_ATTRIBUTION = "Street data © OpenStreetMap contributors (ODbL)"
SYNTHETIC_ATTRIBUTION = "Synthetic ward generated by Upstream — not a real place"


@dataclass
class StreetGraph:
    """An undirected street graph with node coordinates.

    ``edges`` holds index pairs into the node arrays. Local metric coordinates
    (``x``, ``y``) and edge lengths are derived on construction.
    """

    name: str
    lat: np.ndarray
    lon: np.ndarray
    edges: np.ndarray
    synthetic: bool
    attribution: str
    origin: tuple[float, float] | None = None
    x: np.ndarray = field(init=False, repr=False)
    y: np.ndarray = field(init=False, repr=False)
    length: np.ndarray = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self.lat = np.asarray(self.lat, dtype=float)
        self.lon = np.asarray(self.lon, dtype=float)
        self.edges = np.asarray(self.edges, dtype=np.int64).reshape(-1, 2)
        if self.origin is None:
            self.origin = (float(self.lat.mean()), float(self.lon.mean()))
        self.origin = (float(self.origin[0]), float(self.origin[1]))
        self.x, self.y = project(self.lat, self.lon, self.origin)
        a, b = self.edges[:, 0], self.edges[:, 1]
        self.length = np.hypot(self.x[a] - self.x[b], self.y[a] - self.y[b])

    @property
    def n_nodes(self) -> int:
        return int(self.lat.shape[0])

    @property
    def n_edges(self) -> int:
        return int(self.edges.shape[0])

    @property
    def xy(self) -> np.ndarray:
        return np.column_stack([self.x, self.y])

    def point_on_edge(self, edge: int, frac: float) -> tuple[float, float]:
        """Metric (x, y) of the point ``frac`` of the way along ``edge``."""
        a, b = self.edges[edge]
        return (
            float(self.x[a] + frac * (self.x[b] - self.x[a])),
            float(self.y[a] + frac * (self.y[b] - self.y[a])),
        )

    def to_latlon(self, x, y):
        return unproject(x, y, self.origin)

    def nx_graph(self) -> nx.Graph:
        g = nx.Graph()
        g.add_nodes_from(range(self.n_nodes))
        for i, (a, b) in enumerate(self.edges):
            g.add_edge(int(a), int(b), length=float(self.length[i]), edge=i)
        return g

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "synthetic": self.synthetic,
            "attribution": self.attribution,
            "origin": list(self.origin),
            "nodes": [[round(float(la), 7), round(float(lo), 7)] for la, lo in zip(self.lat, self.lon)],
            "edges": self.edges.tolist(),
        }

    @classmethod
    def from_dict(cls, d: dict) -> "StreetGraph":
        nodes = np.asarray(d["nodes"], dtype=float).reshape(-1, 2)
        return cls(
            name=d["name"],
            lat=nodes[:, 0],
            lon=nodes[:, 1],
            edges=np.asarray(d["edges"], dtype=np.int64),
            synthetic=bool(d.get("synthetic", False)),
            attribution=d.get("attribution", ""),
            origin=tuple(d["origin"]) if d.get("origin") else None,
        )

    def save(self, path: str | Path) -> None:
        Path(path).write_text(json.dumps(self.to_dict()))


def _clean(lat, lon, edges, min_len_m: float = 0.5):
    """Drop self-loops, duplicate and near-zero edges; keep the largest
    connected component; reindex nodes compactly."""
    lat = np.asarray(lat, dtype=float)
    lon = np.asarray(lon, dtype=float)
    origin = (float(lat.mean()), float(lon.mean()))
    x, y = project(lat, lon, origin)
    seen: set[tuple[int, int]] = set()
    kept: list[tuple[int, int]] = []
    for a, b in edges:
        a, b = int(a), int(b)
        if a == b:
            continue
        key = (a, b) if a < b else (b, a)
        if key in seen:
            continue
        if math.hypot(x[a] - x[b], y[a] - y[b]) < min_len_m:
            continue
        seen.add(key)
        kept.append(key)
    if not kept:
        raise ValueError("street graph has no usable edges")
    g = nx.Graph()
    g.add_edges_from(kept)
    comp = max(nx.connected_components(g), key=len)
    old = sorted(comp)
    remap = {o: i for i, o in enumerate(old)}
    new_edges = [(remap[a], remap[b]) for a, b in kept if a in remap and b in remap]
    return lat[old], lon[old], np.asarray(new_edges, dtype=np.int64)


def synthetic_streets(
    seed: int = 11,
    cols: int = 14,
    rows: int = 10,
    spacing: float = 68.0,
    jitter: float = 9.0,
    drop_frac: float = 0.16,
    diagonal_frac: float = 0.05,
    stub_frac: float = 0.12,
) -> StreetGraph:
    """Generate a dense, irregular old-city ward: a jittered grid of lanes with
    missing links, a few diagonal lanes and dead-end gullies, plus one main
    road that always runs across the middle."""
    rng = np.random.default_rng(seed)
    xs: list[float] = []
    ys: list[float] = []
    for j in range(rows):
        for i in range(cols):
            xs.append(i * spacing + rng.uniform(-jitter, jitter))
            ys.append(j * spacing + rng.uniform(-jitter, jitter))
    main_row = rows // 2

    def nid(i: int, j: int) -> int:
        return j * cols + i

    edges: list[tuple[int, int]] = []
    for j in range(rows):
        for i in range(cols):
            if i + 1 < cols and (j == main_row or rng.random() > drop_frac):
                edges.append((nid(i, j), nid(i + 1, j)))
            if j + 1 < rows and rng.random() > drop_frac:
                edges.append((nid(i, j), nid(i, j + 1)))
    for j in range(rows - 1):
        for i in range(cols - 1):
            r = rng.random()
            if r < diagonal_frac:
                if rng.random() < 0.5:
                    edges.append((nid(i, j), nid(i + 1, j + 1)))
                else:
                    edges.append((nid(i + 1, j), nid(i, j + 1)))
            elif r < diagonal_frac + stub_frac:
                # a dead-end gully from one corner into the block
                ci, cj = (i + rng.integers(0, 2), j + rng.integers(0, 2))
                corner = nid(int(ci), int(cj))
                dx = (i + 0.5 - ci) * spacing
                dy = (j + 0.5 - cj) * spacing
                f = rng.uniform(0.55, 0.85)
                xs.append(xs[corner] + f * dx)
                ys.append(ys[corner] + f * dy)
                edges.append((corner, len(xs) - 1))
    x = np.asarray(xs) - np.mean(xs)
    y = np.asarray(ys) - np.mean(ys)
    lat, lon = unproject(x, y, (0.0, 0.0))
    lat, lon, e = _clean(lat, lon, edges)
    return StreetGraph(
        name="Synthetic ward (offline demo grid)",
        lat=lat,
        lon=lon,
        edges=e,
        synthetic=True,
        attribution=SYNTHETIC_ATTRIBUTION,
        origin=(0.0, 0.0),
    )


def load_overpass_json(src: str | Path | dict, name: str | None = None,
                       keep: frozenset[str] = HIGHWAY_KEEP) -> StreetGraph:
    """Build a street graph from an Overpass API JSON response
    (``[out:json]; way[highway](bbox); (._;>;); out body;``)."""
    if isinstance(src, dict):
        data = src
    else:
        data = json.loads(Path(src).read_text())
        name = name or Path(src).stem
    coords: dict[int, tuple[float, float]] = {}
    ways = []
    for el in data.get("elements", []):
        if el.get("type") == "node" and "lat" in el and "lon" in el:
            coords[int(el["id"])] = (float(el["lat"]), float(el["lon"]))
        elif el.get("type") == "way":
            tags = el.get("tags", {})
            if tags.get("highway") in keep and tags.get("area") != "yes":
                ways.append(el.get("nodes", []))
    index: dict[int, int] = {}
    lat: list[float] = []
    lon: list[float] = []

    def idx(osm_id: int) -> int:
        if osm_id not in index:
            index[osm_id] = len(lat)
            lat.append(coords[osm_id][0])
            lon.append(coords[osm_id][1])
        return index[osm_id]

    edges = []
    for nodes in ways:
        for a, b in zip(nodes[:-1], nodes[1:]):
            if a in coords and b in coords:
                edges.append((idx(int(a)), idx(int(b))))
    if not edges:
        raise ValueError("no highway ways found in Overpass data")
    lat_a, lon_a, e = _clean(lat, lon, edges)
    return StreetGraph(name=name or "OpenStreetMap streets", lat=lat_a, lon=lon_a, edges=e,
                       synthetic=False, attribution=OSM_ATTRIBUTION)


def load_geojson(src: str | Path | dict, name: str | None = None,
                 attribution: str = OSM_ATTRIBUTION) -> StreetGraph:
    """Build a street graph from GeoJSON LineString / MultiLineString features.
    Coordinates shared between lines (to 1e-7 degrees) become junctions."""
    if isinstance(src, dict):
        data = src
    else:
        data = json.loads(Path(src).read_text())
        name = name or Path(src).stem
    index: dict[tuple[float, float], int] = {}
    lat: list[float] = []
    lon: list[float] = []

    def idx(lo: float, la: float) -> int:
        key = (round(la, 7), round(lo, 7))
        if key not in index:
            index[key] = len(lat)
            lat.append(key[0])
            lon.append(key[1])
        return index[key]

    feats = data["features"] if data.get("type") == "FeatureCollection" else [data]
    edges = []
    for f in feats:
        geom = f.get("geometry") or {}
        if geom.get("type") == "LineString":
            lines = [geom["coordinates"]]
        elif geom.get("type") == "MultiLineString":
            lines = geom["coordinates"]
        else:
            continue
        for line in lines:
            for p, q in zip(line[:-1], line[1:]):
                edges.append((idx(p[0], p[1]), idx(q[0], q[1])))
    if not edges:
        raise ValueError("no LineString features found")
    lat_a, lon_a, e = _clean(lat, lon, edges)
    return StreetGraph(name=name or "Streets", lat=lat_a, lon=lon_a, edges=e,
                       synthetic=False, attribution=attribution)


def load_streets(path: str | Path) -> StreetGraph:
    """Load any supported street file, dispatching on its content."""
    data = json.loads(Path(path).read_text())
    if "elements" in data:
        return load_overpass_json(data, name=Path(path).stem)
    if data.get("type") in ("FeatureCollection", "Feature"):
        return load_geojson(data, name=Path(path).stem)
    if "nodes" in data and "edges" in data:
        return StreetGraph.from_dict(data)
    raise ValueError(f"unrecognised street file format: {path}")


USER_AGENT = "upstream-hackathon/0.1 (water-safety research prototype)"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
OVERPASS_URL = "https://overpass-api.de/api/interpreter"


def _http(url: str, data: bytes | None = None, timeout: float = 120.0) -> bytes:
    req = urllib.request.Request(url, data=data, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310 (fixed https hosts)
        return resp.read()


def bbox_around(lat: float, lon: float, radius_m: float) -> tuple[float, float, float, float]:
    """(south, west, north, east) of a square of half-side ``radius_m``."""
    dlat = radius_m / 111_320.0
    dlon = radius_m / (111_320.0 * math.cos(math.radians(lat)))
    return (lat - dlat, lon - dlon, lat + dlat, lon + dlon)


def geocode(place: str) -> tuple[float, float, str]:
    """Look a place name up with Nominatim. Returns (lat, lon, display_name)."""
    q = urllib.parse.urlencode({"q": place, "format": "jsonv2", "limit": 1})
    hits = json.loads(_http(f"{NOMINATIM_URL}?{q}", timeout=30))
    if not hits:
        raise ValueError(f"Nominatim found nothing for {place!r}")
    return float(hits[0]["lat"]), float(hits[0]["lon"]), hits[0].get("display_name", place)


def overpass_query(bbox: tuple[float, float, float, float], timeout: int = 90) -> str:
    s, w, n, e = bbox
    return (f"[out:json][timeout:{timeout}];"
            f'way["highway"]({s:.7f},{w:.7f},{n:.7f},{e:.7f});'
            "(._;>;);out body;")


def fetch_osm(bbox: tuple[float, float, float, float], timeout: int = 90) -> dict:
    """Download raw highway data for ``bbox`` = (south, west, north, east)."""
    body = urllib.parse.urlencode({"data": overpass_query(bbox, timeout)}).encode()
    return json.loads(_http(OVERPASS_URL, data=body, timeout=timeout + 30))
